CREATE TABLE "app_aso_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"app_id" uuid NOT NULL,
	"category" varchar(100),
	"differentiator" text,
	"key_features" jsonb,
	"main_benefit" text,
	"one_liner" varchar(300),
	"problem" text,
	"pain_points" jsonb,
	"target_audience" text,
	"user_language" text,
	"competitive_advantage" text,
	"competitors" jsonb,
	"positioning" varchar(50),
	"brand_voice_example" text,
	"tone" varchar(50),
	"words_to_avoid" jsonb,
	"words_to_include" jsonb,
	"awards" jsonb,
	"download_count" varchar(50),
	"press_quotes" jsonb,
	"testimonials" jsonb,
	"free_features" jsonb,
	"premium_features" jsonb,
	"price" varchar(100),
	"pricing_model" varchar(50),
	"exclude_keywords" jsonb,
	"long_tail_keywords" jsonb,
	"must_include_keywords" jsonb,
	CONSTRAINT "app_aso_profiles_appId_unique" UNIQUE("app_id")
);
--> statement-breakpoint
ALTER TABLE "app_aso_profiles" ADD CONSTRAINT "app_aso_profiles_app_id_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."apps"("id") ON DELETE cascade ON UPDATE no action;